package com.home.soa.xsdtypes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-26T21:59:00.231+05:30
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://com.home.soa", name = "Employee")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Employee {

    @WebMethod(operationName = "GetEmployeeDetail", action = "http://com.home.soa/Employee/GetEmployeeDetail")
    @WebResult(name = "EmployeeResponse", targetNamespace = "http://com.home.soa", partName = "result")
    public EmployeeResponseMessage getEmployeeDetail(
        @WebParam(partName = "parameters", name = "EmployeeRequest", targetNamespace = "http://com.home.soa")
        EmployeeRequestMessage parameters
    );
}
